/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.amprogramacion.enterprisechatclient;

import java.net.Socket;
import java.util.HashMap;
import org.json.simple.JSONObject;

/**
 *
 * @author Angelmp2
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    String user;
    Conexion conexion;
    String emisor;

    public Chat() {
        initComponents();
    }

    public String getUser() {
        return user;
    }

    public Conexion getConexion() {
        return conexion;
    }

    public void setConexion(Conexion conexion) {
        this.conexion = conexion;
    }

    public void setUser(String user) {
        this.user = user;
        txtHablandoCon.setText("Hablando con " + this.user);
        this.setTitle("Hablando con " + this.user);
    }

    public String getEmisor() {
        return emisor;
    }

    public void setEmisor(String emisor) {
        this.emisor = emisor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chatTxt = new javax.swing.JTextArea();
        txtEnviar = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        txtHablandoCon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        chatTxt.setColumns(20);
        chatTxt.setRows(5);
        jScrollPane1.setViewportView(chatTxt);

        txtEnviar.setToolTipText("");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtHablandoCon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHablandoCon.setText("Hablando con");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtHablandoCon)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtHablandoCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        String msg = txtEnviar.getText();
        EnviarMensajeChat(msg, false);
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.out.println("Se cierra la ventana de chat con " + this.user);
        Inicio.chats.remove(this.user);
        EnviarMensajeChat("<- El usuario ha cerrado la ventana de chat.", true);
    }//GEN-LAST:event_formWindowClosed

    public void RecibirMensaje(String user, String msg) {
        String texto_actual = chatTxt.getText();
        if (texto_actual.equals("")) {
            chatTxt.setText("[" + user + "] " + msg);
        } else {
            chatTxt.setText(chatTxt.getText() + "\r\n[" + user + "] " + msg);
        }
    }

    public void EnviarMensajeChat(String msg, boolean logout) {
        JSONObject obj = new JSONObject();
        JSONObject params_send = new JSONObject();
        obj.put("command", "Chat");
        params_send.put("UsuarioEmisor", getEmisor());
        params_send.put("UsuarioReceptor", getUser());
        params_send.put("Mensaje", msg);
        if (logout == true) {
            params_send.put("Logout", true);
        } else {
            params_send.put("Logout", false);
        }
        obj.put("params", params_send);
        Receptor.send(this.conexion.socket, obj.toJSONString());
        txtEnviar.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JTextArea chatTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEnviar;
    private javax.swing.JLabel txtHablandoCon;
    // End of variables declaration//GEN-END:variables
}
