/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.amprogramacion.enterprisechatclient;

import org.json.simple.JSONObject;

/**
 *
 * @author Angelmp2
 */
public class DialogoUsername extends javax.swing.JFrame {

    Receptor receptor;

    public DialogoUsername(Receptor receptor) {
        this.receptor = receptor;
        initComponents();
    }

    /**
     * Creates new form DialogoUsername
     */
    public DialogoUsername() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnCambiarUsername = new javax.swing.JButton();

        setTitle("Nombre de usuario");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Por favor, introduce un nombre de usuario:");

        txtUser.setToolTipText("");

        btnCambiarUsername.setText("Cambiar nombre de usuario");
        btnCambiarUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnCambiarUsername))
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarUsernameActionPerformed
        // TODO add your handling code here:
        JSONObject obj = new JSONObject();
        JSONObject params_send = new JSONObject();
        obj.put("command", "SetUsername");
        params_send.put("username", txtUser.getText());
        obj.put("params", params_send);
        this.receptor.send(this.receptor.socket, obj.toJSONString());
        btnCambiarUsername.setEnabled(false);
        btnCambiarUsername.setText("Espera...");
    }//GEN-LAST:event_btnCambiarUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarUsername;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
