/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.amprogramacion.enterprisechatclient;

import static es.amprogramacion.enterprisechatclient.Receptor.send;
import java.io.IOException;
import java.net.Socket;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import org.json.simple.JSONObject;

/**
 *
 * @author Angelmp2
 */
public class Inicio extends javax.swing.JFrame {

    int numclicks = 0;
    String lastuser = "";
    String myUsername = "";
    public static Conexion con = new Conexion();
    public static final HashMap<String, Chat> chats = new HashMap<>();

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    public String getMyUsername() {
        return myUsername;
    }

    public void setMyUsername(String myUsername) {
        this.myUsername = myUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCambiarNombreUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnHeaderActualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selecciona un usuario de la lista:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jList1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("Archivo");
        jMenu1.setActionCommand("ArchivoCommand");

        btnCambiarNombreUsuario.setText("Cambiar nombre de usuario");
        btnCambiarNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarNombreUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(btnCambiarNombreUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuarios online");
        jMenu2.setActionCommand("ListaUsuariosCommand");

        btnHeaderActualizar.setText("Actualizar");
        btnHeaderActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeaderActualizarActionPerformed(evt);
            }
        });
        jMenu2.add(btnHeaderActualizar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 323, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (evt.getClickCount() == 2) {
            String user_seleccionado = (String) Inicio.jList1.getSelectedValue();
            Chat chat = new Chat();
            chat.setUser(user_seleccionado);
            chat.setVisible(true);
            chat.setConexion(con);
            chat.setEmisor(getMyUsername());
            chats.put(user_seleccionado, chat);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseReleased

    private void btnHeaderActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeaderActualizarActionPerformed
        JSONObject obj = new JSONObject();
        obj.put("command", "UserList");
        send(con.socket, obj.toJSONString());
    }//GEN-LAST:event_btnHeaderActualizarActionPerformed

    private void btnCambiarNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarNombreUsuarioActionPerformed
        con.receptor.dg.setVisible(true);
        con.receptor.dg.btnCambiarUsername.setEnabled(true);
        con.receptor.dg.btnCambiarUsername.setText("Cambiar nombre de usuario");
        con.receptor.dg.txtUser.setText(con.inicio.getMyUsername());
    }//GEN-LAST:event_btnCambiarNombreUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicio inicio = new Inicio();
                inicio.setVisible(true);
                Config.CrearConfiguracion();
                try {
                    con.ConectarSocket(inicio);
                } catch (IOException e) {
                    System.out.println("No se puede conectar.");
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCambiarNombreUsuario;
    private javax.swing.JMenuItem btnHeaderActualizar;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
